# Generated by Django 5.0.6 on 2025-05-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_owner_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='owner_photos/'),
        ),
    ]
