# Generated by Django 5.0.6 on 2025-05-07 06:56

import owner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_alter_owner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, default='owner_photos/default.jpg', null=True, upload_to=owner.models.owner_photo_path),
        ),
    ]
