# Generated by Django 5.0.6 on 2025-05-12 06:49

import owner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_alter_owner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=owner.models.owner_photo_path),
        ),
    ]
