# Generated by Django 5.0.6 on 2025-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
