# Generated by Django 5.0.6 on 2025-05-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
