# Generated by Django 5.0.6 on 2025-05-07 06:43

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=employee.models.employee_photo_path),
        ),
    ]
