# Generated by Django 5.0.6 on 2025-05-07 06:56

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='employee_photos/default.jpg', null=True, upload_to=employee.models.employee_photo_path),
        ),
    ]
